CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL UNIQUE,
    nickname    VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spaces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS shelves (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    space_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (space_id) REFERENCES spaces(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS boxes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    shelf_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shelf_id) REFERENCES shelves(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    expiration_period_days INT,
    price       NUMERIC(12,0),
    serial_mode VARCHAR(10) NOT NULL DEFAULT 'NONE',
    serial_prefix VARCHAR(100),
    serial_padding_length INT NOT NULL DEFAULT 0,
    serial_increment_unit INT NOT NULL DEFAULT 1,
    serial_next_sequence BIGINT NOT NULL DEFAULT 0,
    lot_mode VARCHAR(10) NOT NULL DEFAULT 'NONE',
    lot_vendor_code VARCHAR(100),
    lot_date_format VARCHAR(32) DEFAULT 'yyyyMMdd',
    lot_include_sequence BOOLEAN NOT NULL DEFAULT TRUE,
    lot_sequence_key VARCHAR(32),
    lot_next_sequence INT NOT NULL DEFAULT 0,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_items_expiration_period_days CHECK (expiration_period_days IS NULL OR expiration_period_days > 0),
    CONSTRAINT chk_items_price CHECK (price IS NULL OR price >= 0),
    CONSTRAINT chk_items_serial_mode CHECK (serial_mode IN ('NONE', 'AUTO', 'MANUAL')),
    CONSTRAINT chk_items_lot_mode CHECK (lot_mode IN ('NONE', 'AUTO', 'MANUAL')),
    CONSTRAINT chk_items_serial_padding_length CHECK (serial_padding_length >= 0),
    CONSTRAINT chk_items_serial_increment_unit CHECK (serial_increment_unit > 0),
    CONSTRAINT chk_items_serial_next_sequence CHECK (serial_next_sequence >= 0),
    CONSTRAINT chk_items_lot_next_sequence CHECK (lot_next_sequence >= 0)
);

CREATE TABLE IF NOT EXISTS item_lots (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id     UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    item_id         BIGINT       NOT NULL,
    lot_number      VARCHAR(255) NOT NULL,
    expiration_date DATE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT uq_item_lots_item_lot_number UNIQUE (item_id, lot_number)
);

CREATE INDEX IF NOT EXISTS idx_item_lots_item_id
    ON item_lots (item_id);

CREATE TABLE IF NOT EXISTS stocks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id     UUID      DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    item_id         BIGINT    NOT NULL,
    space_id        BIGINT    NOT NULL,
    shelf_id        BIGINT,
    box_id          BIGINT,
    lot_id          BIGINT,
    serial_number   VARCHAR(255),
    lot_number      VARCHAR(255),
    expiration_date DATE,
    memo            TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'IN_STOCK',
    is_kept         BOOLEAN NOT NULL DEFAULT FALSE,
    price           NUMERIC(12,0),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id)  REFERENCES items(id),
    FOREIGN KEY (space_id) REFERENCES spaces(id),
    FOREIGN KEY (shelf_id) REFERENCES shelves(id) ON DELETE CASCADE,
    FOREIGN KEY (box_id)   REFERENCES boxes(id)   ON DELETE CASCADE,
    FOREIGN KEY (lot_id)   REFERENCES item_lots(id) ON DELETE SET NULL,
    CONSTRAINT chk_box_requires_shelf CHECK (box_id IS NULL OR shelf_id IS NOT NULL),
    CONSTRAINT chk_stock_status CHECK (status IN ('IN_STOCK', 'DISPATCHED', 'LOST', 'DAMAGED', 'DISPOSED')),
    CONSTRAINT chk_stocks_price CHECK (price IS NULL OR price >= 0),
    CONSTRAINT uq_stocks_item_serial UNIQUE (item_id, serial_number)
);

CREATE INDEX IF NOT EXISTS idx_stocks_lot_id
    ON stocks (lot_id);

CREATE INDEX IF NOT EXISTS idx_stocks_is_kept
    ON stocks (space_id, status, is_kept);

CREATE TABLE IF NOT EXISTS stock_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id      UUID        DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    stock_id         BIGINT      NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    from_space_id    BIGINT,
    from_shelf_id    BIGINT,
    from_box_id      BIGINT,
    to_space_id      BIGINT,
    to_shelf_id      BIGINT,
    to_box_id        BIGINT,
    memo             TEXT,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE,
    FOREIGN KEY (from_space_id) REFERENCES spaces(id),
    FOREIGN KEY (from_shelf_id) REFERENCES shelves(id),
    FOREIGN KEY (from_box_id)   REFERENCES boxes(id),
    FOREIGN KEY (to_space_id)   REFERENCES spaces(id),
    FOREIGN KEY (to_shelf_id)   REFERENCES shelves(id),
    FOREIGN KEY (to_box_id)     REFERENCES boxes(id),
    CONSTRAINT chk_transaction_type CHECK (transaction_type IN ('IN', 'OUT', 'MOVE', 'ADJUST'))
);

CREATE TABLE IF NOT EXISTS images (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id       UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    user_id           BIGINT       NOT NULL,
    storage_path      TEXT         NOT NULL,
    original_filename VARCHAR(255),
    content_type      VARCHAR(100),
    size_bytes        BIGINT,
    content_hash      VARCHAR(64),
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_images_user_hash UNIQUE (user_id, content_hash)
);

CREATE TABLE IF NOT EXISTS item_images (
    item_id       BIGINT    NOT NULL,
    image_id      BIGINT    NOT NULL,
    display_order INT       NOT NULL DEFAULT 0,
    is_primary    BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (item_id, image_id),
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_images (
    stock_id      BIGINT    NOT NULL,
    image_id      BIGINT    NOT NULL,
    display_order INT       NOT NULL DEFAULT 0,
    is_primary    BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (stock_id, image_id),
    FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
);
